### ISSUE TITLE
rcon module does not support factorio servers

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pysrcds#5]
apparently factorio servers do not handle multipart responses properly, so we should account for this

**Comment by pmrowla** [comment]
i think this should be resolved as of 418760a but i do not have a factorio server for testing

**Comment by bendre90** [comment]
Hi Pmrowla,
im the one, who wrote you the email last night about this.
Thanks for your very quick reply.

It still doesnt work - the connection gets established (from factorio logs) but there is no response.
Maybe im doing it just wrong? Here is my code, i tried (just copied the rcon.py, because i dont need all that source dedicated stuff)
```
import rcon
factorio_conn = rcon.RconConnection('192.168.2.130', '30005', '8VY538PM', single_packet_mode=True)
response = factorio_conn.exec_command('/players')

```
If you like to adress this issue further, i happily provide a test server for you:
IP: 85.25.214.109
Rcon Port: 50139
Rcon PW: 0bec77ed
Example commands: "/players" or "/help"
"/player" returns: "Online Players (count):\n Names"
"/help" returns a list of available commands.
(Its an empty test server, so making this public isnt a problem, at least for me..)

Thanks for helping me out!
Greetings
Benni

**Comment by pmrowla** [comment]
I pushed another change that should fix the connection issue. Please test it again and let me know if it works for you now.

```python
Python 3.6.4 (default, Dec 25 2017, 15:23:44)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from srcds.rcon import RconConnection
>>> c = RconConnection('85.25.214.109', port=50139, password='0bec77ed', single_packet_mode=True)
>>> resp = c.exec_command('/players')
>>> str(resp)
"b'Players (5):\\n  bendre\\n  NoliVe\\n  Frozensmoker\\n  DrZoddiak\\n  Stonehouse\\n\\x00\\x00'"
```

**Comment by bendre90** [comment]
Works fine - thank you very much!
